# URL de conexão: localhost indica que está na sua máquina, e 5432 é a porta padrão do Postgres
# obr_db é o nome do banco de dados que você deve criar no seu Postgres (via pgAdmin ou DBeaver)
spring.datasource.url=jdbc:postgresql://localhost:5432/obr_db
spring.datasource.username=postgres
spring.datasource.password=0207

# Driver oficial do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração de Hibernate/JPA (Code-First)
# "update" diz para o Spring criar ou atualizar as tabelas automaticamente quando o app rodar
spring.jpa.hibernate.ddl-auto=update

# Mostra no console do terminal os comandos SQL que o Spring gerar (ótimo para aprender)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true